spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5432/dineops_test?sslmode=disable}
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false
